# Generated by Django 2.2.1 on 2019-05-29 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw_21', '0004_track_band'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='band',
        ),
    ]
