# Generated by Django 2.2.1 on 2019-05-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_21', '0005_remove_track_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.DurationField(),
        ),
    ]
