# Generated by Django 2.2.1 on 2019-05-29 18:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hw_21', '0006_auto_20190529_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='band',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hw_21.MusicBand'),
            preserve_default=False,
        ),
    ]
