# Generated by Django 2.2.1 on 2019-05-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
                ('owner_full_name', models.CharField(max_length=50)),
                ('year_issue', models.IntegerField()),
            ],
        ),
    ]
