# Generated by Django 2.2.1 on 2019-05-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw_21', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='middlename',
            field=models.CharField(default='Alan', max_length=30),
            preserve_default=False,
        ),
    ]
